apiVersion: v1
kind: Pod
metadata:
  name: springboot-multimodule
  labels:
    app: springboot-multimodule
spec:
  restartPolicy: Never
  volumes:
    - name: shared-data
      emptyDir: { }

  containers:
  - name: mongo-db
    image: mongo
    volumeMounts:
      - name: shared-data
        mountPath: /usr/share/mongo

  - name: mongo-service
    image: ajprakash/springboot-mongo
    args: ["--spring.data.mongodb.database=user_db","--spring.data.mongodb.port=27017","--spring.data.mongodb.host=localhost"]

  - name: user-service
    image: ajprakash/springboot-sampleapp
    ports:
      - containerPort: 8280
    args: ["--db.host=localhost", "--db.port=8102"]




