apiVersion: v1
kind: Service
metadata:
  name: springboot-multimodule-service
  namespace: ajprakash
  labels:
    name: springboot-multimodule-service
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the kubectl  service.
  # type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 8080
      nodePort: 30080
  selector:
    name: springboot-multimodule